### ISSUE TITLE
out of range reference

### ISSUE THREAD

**Issue by wr1** [WISDEM/AirfoilPreppy#10]
Dear all, 

thanks for the useful code, there seems to be a minor issue with the Cm addition, see patch below. 

Best regards
W
```
diff --git a/src/airfoilprep.py b/src/airfoilprep.py
index 012747d..b02ccbe 100755
--- a/src/airfoilprep.py
+++ b/src/airfoilprep.py
@@ -343,7 +343,7 @@ class Polar(object):

         found_zero_lift = False

-        for i in range(len(self.cm)):
+        for i in range(len(self.cm)-1):
             if abs(self.alpha[i]) < 20.0 and self.cl[i] <= 0 and self.cl[i+1] >
= 0:
                 p = -self.cl[i] / (self.cl[i + 1] - self.cl[i])
                 cm0 = self.cm[i] + p * (self.cm[i+1] - self.cm[i])
```

**Comment by Ry10** [comment]
Hi, 

Could you post what your inputs are when you get the out of range error? I have been trying to replicate the error and have been unable to do so.  

Thank you for your help!

**Comment by andrewning** [comment]
Ryan,

Perhaps you are short circuiting the if statement in your test and so not testing the i+1 case.  Just looking at the code it looks like you will trigger an out of bounds error when trying to index: i+1 on the last index of the array.  Seems like something simple like this would work to test (or anything where the last index of cl was negative with an angle of attack under 20).
alpha = [0.0, 1.0]
cl = [-6.0, -5.0]
cm = [1.0, 1.0]

**Comment by Ry10** [comment]
Great. Easy fix. I submitted the pull request.
