### ISSUE TITLE
Implementation of optional 3D correction models

### ISSUE THREAD

**Issue by mrosemeier** [WISDEM/AirfoilPreppy#13]
Currently the correction3D method provides merely the Du-Selig model for to correct cl and Eggers for Cd. The implementation of other models would increase the variety of airfoilpreppy such as Snel (for cl) + Eggers (for cd), (2) Lindenburg (for cl) +  Eggers (for cd), (3) Du and Selig (for cl and cd), (4) Chaviaropoulus and Hansen (cl , cd), and (5) Bak (cl, cd, cm). The implementation of the first 4 would be straight forward. However, for the Bak model the airfoil coordinates and relative thickness are required as input.
@Ry10: If you already have an idea how you realize the coordinates implementation for the XFOIL subprocess implementation, I could build on that. Else I would wait for your merge.

**Comment by andrewning** [comment]
Those would be great. One of the reasons for the Python version was to accommodate other correction methods. We do not have any immediate plans to implement any of these, but would accept pull requests. 




I'd wait on Ryan's implementation for the last case.

**Comment by dykesk** [comment]
@mrosemeier where does your recent pull request stand on this issue?

**Comment by mrosemeier** [comment]
@dykesk the recent pull request does not affect this issue. However, I have pushed the latest stage to this [branch](https://github.com/mrosemeier/AirfoilPreppy/tree/3dcorrection).
