### ISSUE TITLE
input airfoil.dat file to airfoilpreppy

### ISSUE THREAD

**Issue by AmrEssam22** [WISDEM/AirfoilPreppy#17]
Hii
I am undergrad working on my graduation project on wind energy. I keep getting error when using my airfoil in the command "python airfoilprep.py **airfoil.dat** --extrap 1"  
the error messages mean that my format for  my airfoil.dat file is not in the readable form for airfoilprep 

I would appreciate if someone can upload an example of the formatted airfoil for airfoilprep usage on python

**Comment by gbarter** [comment]
Sorry for the delay in addressing this.  We have some processes in place to do better.  There is now an [example](https://github.com/WISDEM/AirfoilPreppy/tree/master/example) airfoil polar input file.
