### ISSUE TITLE
[QUESTION] Using AirfoilPreppy from the command line

### ISSUE THREAD

**Issue by CallumG-Ed** [WISDEM/AirfoilPreppy#18]
Hi,

I'm trying to use AirfoilPreppy form the command line as described [here](http://wisdem.github.io/AirfoilPreppy/tutorial.html) to do some extrapolation of high AoA. I downloaded the AeroDyn example input file to test it on from [here](https://openfast.readthedocs.io/en/master/source/user/aerodyn/appendix.html#ad-appendix) and removed a few lines from the Cl/Cd table at the bottom.

When I envoke command: 
`python airfoilprep.py airfoil_3D.dat --extrap 1.3`

An error is returned:
`Traceback (most recent call last):
  File "airfoilprep.py", line 1061, in <module>
    af = Airfoil.initFromAerodynFile(args.src_file)
  File "airfoilprep.py", line 555, in initFromAerodynFile
    numTables = int(f.readline().split()[0])
ValueError: invalid literal for int() with base 10: '!'`

I'd appreciate some support on this if possible.

Cheers
Callum

**Comment by gbarter** [comment]
The file reader was calibrated to an old version of Aerodyn and wasn't robust enough to handle the version you downloaded.  I simplified the reader and provided an [example](https://github.com/WISDEM/AirfoilPreppy/tree/master/example) input polar file.

**Comment by CallumG-Ed** [comment]
Thats awesome!! Thanks so much, I really didn't want to have to reproduce this!
