### ISSUE TITLE
Installation issue: "cannot import name 'Polar' from 'airfoilprep' "

### ISSUE THREAD

**Issue by NasonZ** [WISDEM/AirfoilPreppy#19]
Hi,

I'm having issues with installation.

I've followed up to step 2 of the [WISDEM installation guide](https://github.com/WISDEM/WISDEM) to create a conda environment. I then ran `python test/test_airfoilprep.py` and successfully installed AirfoilPrep.0.1.0 and it dependencies.

However, when running `python test/test_airfoilprep.py` to  I got the error message:

`Traceback (most recent call last):
  File "test/test_airfoilprep.py", line 5, in <module>
    from airfoilprep import Polar, Airfoil
ImportError: cannot import name 'Polar' from 'airfoilprep' 
(C:\Users\Usr\Anaconda3\envs\wisdem-env\lib\site-packages\airfoilprep-0.1.0-py3.7.egg\airfoilprep\__init__.py)`

Any advice on how to resolve this issue would be appreciated as I eager to use your package.
 
Cheers
Nason

**Comment by CallumG-Ed** [comment]
I also have this issue though I installed AirfoilPreppy as a standalone using the setup.py script.

**Comment by gbarter** [comment]
This has been fixed.
