### ISSUE TITLE
add cm to polar class

### ISSUE THREAD

**Issue by dykesk** [WISDEM/AirfoilPreppy#3]
request in #1 for "Regarding the Polar class it would be neat if it also handled coefficient of moment, cm"

**Comment by matsupe** [comment]
I am one more person requesting 'cm's. I tried to blend some airfoils but Airfoilprep.py printed zeros for all 'cm' s.
Thanks for providing your codes publicly.

**Comment by andrewning** [comment]
Ryan has now added this.
