### ISSUE TITLE
Add plot functions to Airfoil/Polar classes (currently plotting is only supported in the CLI)

### ISSUE THREAD

**Issue by whophil** [WISDEM/AirfoilPreppy#6]
It would be nice if plotting functions were added for the Airfoil/Polar classes. Currently plotting is only supported through the command line interface.

For example:
- `Polar.plot()` would plot Cl, Cd, or Cm.
- `Airfoil.plot()` would plot Cl, Cd, or Cm vs. alpha labeled by Reynolds.

I'd be happy to add this.
pchiu@sandia.gov

**Comment by dykesk** [comment]
Hello Phil, I agree those would be great functions to have and if you want to fork our code, modify and do a pull request, we would certainly be happy to have you contribute.

**Comment by andrewning** [comment]
Sorry for the delay in merging, had a more pressing bug to deal with.  Thanks for your contribution!
